# Launch simple postgres server
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: asdf1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"